services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  search-api:
    build:
      context: ./search-api
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./search-api:/app # Mount current directory for hot reloading
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/your_database
      - PYTHONDONTWRITEBYTECODE=1 # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1 # Prevents Python from buffering stdout and stderr

  search-ui:
    build:
      context: ./search-ui
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./search-ui:/app
      - /search-ui/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./search-ui/.env.local

  dagster-daemon:
    build:
      context: ./dagster
      dockerfile: Dockerfile
    volumes:
      - ./dagster:/opt/dagster/app
    environment:
      - DAGSTER_HOME=/opt/dagster/app
    command: ["dagster-daemon", "run"]

  dagster-webserver:
    build:
      context: ./dagster
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dagster:/opt/dagster/app
    environment:
      - DAGSTER_HOME=/opt/dagster/app
    command: ["dagit", "-h", "0.0.0.0", "-p", "3000"]
